// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_play_test = "CgkIp6SwmNsTEAIQCA"; // <GPGSID>
        public const string achievement_scythe = "CgkIp6SwmNsTEAIQDQ"; // <GPGSID>
        public const string achievement_big_fish = "CgkIp6SwmNsTEAIQBA"; // <GPGSID>
        public const string achievement_big_flock = "CgkIp6SwmNsTEAIQBQ"; // <GPGSID>
        public const string achievement_first_winter = "CgkIp6SwmNsTEAIQAg"; // <GPGSID>
        public const string achievement_great_flock = "CgkIp6SwmNsTEAIQBw"; // <GPGSID>
        public const string achievement_teenager = "CgkIp6SwmNsTEAIQCQ"; // <GPGSID>
        public const string achievement_seafood = "CgkIp6SwmNsTEAIQCg"; // <GPGSID>
        public const string achievement_long_winter = "CgkIp6SwmNsTEAIQAw"; // <GPGSID>
        public const string achievement_arnivore = "CgkIp6SwmNsTEAIQCw"; // <GPGSID>
        public const string leaderboard_woolen_fabric = "CgkIp6SwmNsTEAIQAQ"; // <GPGSID>
        public const string achievement_hayfork = "CgkIp6SwmNsTEAIQDg"; // <GPGSID>
        public const string achievement_first_batch_of_fabric = "CgkIp6SwmNsTEAIQBg"; // <GPGSID>
        public const string achievement_dead_sea = "CgkIp6SwmNsTEAIQDA"; // <GPGSID>

}

